### ISSUE TITLE
华为荣耀手机拍照打不开

### ISSUE THREAD

**Issue by wanghuitaolove** [wsy858/android-headimage-cliper#1]

**Comment by wsy858** [comment]
错误信息是什么？截个图

**Comment by geofferysun** [comment]
请问解决了吗？我也遇到。不管相机还是相册，裁切时候都是一片黑，取不到数据

**Comment by wsy858** [comment]
你好，目前有可能是在6.0版本上没有添加访动态问外部存储权限， 示例代码已经更新，请查看问题是否依然存在！

**Comment by wsy858** [comment]
你好，目前有可能是在6.0版本上没有添加动态访问外部存储的权限， 示例代码已经更新，请查看问题是否依然存在！

**Comment by Zziv** [comment]
华为系列的手机，拍照后，返回裁剪时都是黑屏
